### ISSUE TITLE
Allow users to select individual files to view in the image viewer

### ISSUE THREAD

**Issue by cBridges851** [cBridges851/tkinter-image-viewer#10]
**Is your feature request related to a problem? Please describe.**
I have to create a folder to put images inside currently to see them in the image viewer.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/54030147/194705487-891bc1ef-deae-435e-b682-92932b34f4f3.png)
Above "Open folder" in the menu, I'd like an "Open file" option.

When I click this, it should open my file explorer, and from there I should be able to select one or multiple images.

When I click "Open", I should see the image(s) I selected in the image viewer.

**Describe alternatives you've considered**
Creating a folder to put images inside is one alternative I guess, but I feel that being able to select individual file(s) would provide a better user experience.

Something that would also fix the problem, although it could be a complementary feature as opposed to an alternative, is allowing users to right click an image file and select "Open with Chrispy Image Viewer", similar to what you can do with VSCode:
![image](https://user-images.githubusercontent.com/54030147/194705936-fb58dc4a-7d64-462d-a3c5-71bec6815f02.png)
However, I'm unsure of the scope of that, so I'll note to investigate that. If anyone has any thoughts on this, feel free to share below!

Likewise, if you think there is a better solution to this problem as a whole, feel free to share below!

This issue is open to being worked on for Hacktoberfest, comment below if you have any questions and/or would like to work on it! First come first serve.

**Comment by yagueto** [comment]
Hi! I am willing to help with creating the "open file" option (unfortunately not a windows user, so cannot help with the file explorer integration :grimacing:)

**Comment by sagamantus** [comment]
Hey! I have an idea for this feature and would love to work on this issue.

**Comment by cBridges851** [comment]
Hi @yagueto, thank you for your interest in this issue! I've only used and developed the image viewer on Windows, so I'd be very curious as to how well the image viewer works on Mac or Linux. Would you mind taking a look at it on whichever operating system you have? I'd be very curious as to how the current "open folder" option works, since that opens the file explorer. Thank you 😊

**Comment by yagueto** [comment]
I've just tested it on Linux and raised the issue #11 accordingly.

The "open folder" button works as in Windows, so I can help creating the "open file"

**Comment by cBridges851** [comment]
You're a star - thank you for taking a look, I really appreciate it! 

Since the open folder button works for you, I'm more than happy to assign this task to you! Good luck, let me know if I can be of any assistance 😊
