### ISSUE TITLE
[BUG] Crash in linux

### ISSUE THREAD

**Issue by yagueto** [cBridges851/tkinter-image-viewer#11]
**Describe the bug**
Program fails to start on Linux with ```_tkinter.TclError: couldn't recognize data in image file "favicon.ico"```

**To Reproduce**
1. Launch via `python image-viewer.py`
2. See error

**Expected behavior**
It should start :upside_down_face: 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Arch Linux, KDE Desktop

**Additional context**
According to [this stackoverflow question](https://stackoverflow.com/questions/11176638/tkinter-tclerror-error-reading-bitmap-file/11180300), Linux does not accept .ico files. We could check on which OS we are running and use a .png/.gif/.xbm for linux

**Comment by cBridges851** [comment]
This is a very interesting bug, thank you for opening this issue! I think the solution you've suggested based on what's in that Stackoverflow and other places I've looked online is probably the most suitable way to get around it, or change the icon to a file type that is supported by all OSs.

Would you like to be assigned to this issue?

**Comment by yagueto** [comment]
Sure!

**Comment by cBridges851** [comment]
Fantastic, thank you!

**Comment by cBridges851** [comment]
Going to do a little more investigation around the best way to approach this following on from the change made in #15 (see the approval for more details), will ask on StackOverflow shortly and will update this comment with the link.

**Comment by cBridges851** [comment]
Hey @yagueto, sorry I've taken a while to get back to you on this one!

I'm not finding any reason why `self.root.tk.call(...)` shouldn't be used, bar the fact that there tends to be something on Tkinter to handle things. 

To compare the 2 solutions I'd say:
Checking OS method:
🙂 I'd personally say it's a lot more readable
☹ Means that we have to have two files for the icon

`self.root.tk.call(...)` method:
🙂 One file stored
☹ It's less clear what the line is doing

I'm not really seeing any major advantage for one solution over the other and I want to be mindful of your time, so I think we should be able to leave it as it is, although I'll add a comment above the `self.root.tk.call(...)` line to just clarify what it's doing and why. I'll close this issue, but feel free to reopen it if you disagree!

Thank you for identifying this bug in the first place and creating this issue, it's much appreciated and gave me the opportunity to learn something here! If you're looking to do more stuff for Hacktoberfest, I'll be opening some more issues on Monday, or feel free to let me know if there's something you'd like to get better at and I'll see about creating an issue in one of my repos which can help with that 😊

All the best!
