### ISSUE TITLE
Arrow buttons move when the window is resized due to really long file names

### ISSUE THREAD

**Issue by cBridges851** [cBridges851/tkinter-image-viewer#14]
**Describe the bug**
When you have a file name that's really long, the image viewer's window automatically resizes to fit the label. This causes the arrow buttons to move:

**To Reproduce**
1. Either edit a file name in the ./images folder in the repo so it's really long, or open a folder that has a file with a long filename
2. Click on an arrow button to move onto the next image
3. If the filename is different in length, the window will automatically resize, and the buttons will move as a result

**Expected behavior**
The image viewer window size should be fixed, meaning the arrows don't change position.

**Screenshots**
![arrow buttons moving](https://user-images.githubusercontent.com/54030147/194809360-f1ff1d04-41ff-4e44-9045-1aa18e8d2b38.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
My recommendation for this would be to do something along the lines of setting the window width based on the longest filename.
My initial thought was to wrap the filename, so it would go onto multiple lines instead, but I think we'd get a similar problem with the height.
However, if you can think of a better solution, please do implement it!

~~This issue is open to being worked on for Hacktoberfest, comment below if you have any questions and/or would like to work on it! First come first serve.~~ Currently a PR up for this, soon to be merged

**Comment by QueTeddy** [comment]
is it okay I truncate the image name using an ellipsis if it is longer than a particular length?

for example ./images/animal aaa...

**Comment by cBridges851** [comment]
Hi @QueTeddy, a PR has been made already for this issue (#16), it just hadn't been connected to this. I do apologise! 

However, if you'd like to contribute to this repo in another way, feel free to create an issue for any bugs you find or features you think would be good to add to the image viewer, or let me know if you're looking to get some practise in a particular aspect of Tkinter/Python and I'll see about coming up with some ideas. I'll also be adding more issues to this repo during the course of Hacktoberfest, so do keep an eye out!

**Comment by cBridges851** [comment]
Closed by #16
