### ISSUE TITLE
Adding some data in the viewr 

### ISSUE THREAD

**Issue by ahmedheltaher** [cBridges851/tkinter-image-viewer#17]
- **like show the index of the image like `3/7` like the bottom arrow**
- **and small button to show some meta data about the image like the top right Arrow** 

![autodraw 10_12_2022](https://user-images.githubusercontent.com/42752070/195413590-04678726-055f-4cb8-9364-7763cfba3ec3.png)

_I Can Work on this (if you are willing to add this feature)_

**Comment by cBridges851** [comment]
Hi @ahmedheltaher, great to see you here again! I really like what you've suggested here, I think it would be really good for the user to see which image they are on as well as the information associated with the picture as part of the metadata, and the fact it can be viewed via the button in the top right doesn't flood the main image viewer window with text. 

Thank you for the design (that really helps!) and the suggestion, I'm more than happy for this feature to be added to the image viewer and for you to work on it 😊! I will go ahead and assign you to it now!

A note to consider when you're working on this, there's a PR up currently which is very close to merge around opening specific files: https://github.com/cBridges851/tkinter-image-viewer/pull/12. I'd recommend ensuring that your solution will be able to handle the changes made in here.

Thanks again!

**Comment by ahmedheltaher** [comment]
Thank you.

And sure i will make sure these changes will be compatible with the new pr
