### ISSUE TITLE
Saving Themes

### ISSUE THREAD

**Issue by cBridges851** [cBridges851/tkinter-image-viewer#18]
**Is your feature request related to a problem? Please describe.** 
When opening the application, it always opens in dark mode, even though I may have set the application to light mode previously.  

**Describe the solution you'd like** 
When I open the application, I would like the theme to always be the one I used last. If I open the application, set the theme to light mode, close the program and reopen it, I would expect it to stay in light mode. Likewise, if I keep it in dark mode, I would always expect the application to be in dark mode. 

I would like the theme to be saved into a JSON file in the repo. 

**Describe alternatives you've considered** 
The theme could be saved into a CSV file, but I think JSON would be easier to handle (based on experience) and would be easier to scale and maintain in the future. Feel free to disagree with me here though! 

Another alternative could be a database, but I think that would be a bit over-the-top at this stage.  

This issue is open to being worked on for Hacktoberfest, comment below if you have any questions and/or would like to work on it! First come first serve.

**Comment by siddharth595** [comment]
@cBridges851 I will try to give my best on this. Can you please assign this to me?

**Comment by cBridges851** [comment]
@siddharth595 of course, will assign you now 😊! Good luck, let me know if you need anything, I'm more than happy to help 😊!

**Comment by siddharth595** [comment]
Hey @cBridges851, I guess this issue can be closed as the feature has been implemented.

**Comment by cBridges851** [comment]
Ah yes, of course! Thank you 😊
