### ISSUE TITLE
Splitting Up The Code - OOP Challenge

### ISSUE THREAD

**Issue by cBridges851** [cBridges851/tkinter-image-viewer#19]
In the codebase, we have one class called ImageViewer which handles EVERYTHING to do with the program. E.g. the display of images, the navigation (left and right buttons), opening files/folders, theming. 

In software engineering, there's an acronym called SOLID which establishes 5 practices that help projects to be maintainable and grow. The "S" in SOLID stands for single-responsibility principle, meaning classes and methods should have 1 responsibility, which ImageViewer clearly doesn't have! 

What I'd like to see, ideally from a new contributor who is relatively new to OOP and SOLID, is each of the responsibilities the ImageViewer class has being split out into individual classes. For example, the navigation functionality should be split out into a Navigator class. These classes should be in their own files (so one class per file). 

While this isn't adding new functionality to the image viewer, this change will be incredibly valuable – splitting out the existing functionality into classes will make the codebase much easier for people to understand, and reduce the likelihood of headaches caused from merge conflicts. At the moment, image-viewer.py has a lot of footfall because every bit of new functionality is being added in there, making merge conflicts more likely. 

For further reading: 

[SOLID: The First 5 Principles of Object Oriented Design, DigitalOcean](https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design) 

[Introduction to OOP, the main concepts for this will be classes and objects](https://www.geeksforgeeks.org/introduction-of-object-oriented-programming/) 

OOP Naming Conventions: 
Classes should be a noun since they are representing a real world object. Think of the classes as like job roles, what is the class responsible for? E.g. A Navigator class would be responsible for navigating. 

Methods should be a verb (doing word) since the represent behaviour. You'll see this in the code currently, like `move_left` and `move_right` 

This issue is open to being worked on for Hacktoberfest, comment below if you have any questions and/or would like to work on it! First come first serve. Feel free to discuss and clarify below how existing functionality can be split before implementing.

**Comment by databugs** [comment]
Hello @cBridges851, I am relatively new to Open Source,  OOP,  and SOLID. It will be great to work on this as part of Hacktoberfest and as my first open-source contribution.

**Comment by cBridges851** [comment]
Hey @databugs, thank you for commenting! You are more than welcome to work on this issue, I'll assign you now 😊!

Have fun and let me know if you need anything, I'm more than happy to help!
