### ISSUE TITLE
Move hard-coded UI strings to a JSON File 

### ISSUE THREAD

**Issue by cBridges851** [cBridges851/tkinter-image-viewer#28]
This is an improvement to the existing code. 

At the moment, the text that is displayed in the UI (e.g. "No images found", the text in the menu) is found in the code itself. 

In the future, it would be great for the image viewer to be accessible in more languages than just English. When this move is made, it would not be a wise idea to have the UI strings set in the code itself, or else we're going to end up with a lot of if statements everywhere! 

A cleaner way to tackle this would be to have the strings in a JSON file (one JSON file per language), and then open the appropriate one based on the language, and the strings would be retrieved from that. 

Don't worry about implementing the whole "language mechanics" (i.e. rendering strings based on the language the user has selected). For now, just move all the UI strings to a JSON file and retrieve strings from it. 

e.g. 

Instead of having "No image found" hardcoded here 
![image](https://user-images.githubusercontent.com/54030147/197471727-56c1edb5-1308-444e-bb9c-37f6401cb40e.png)

It would have something that would get that string from the JSON file. 

You can find out more about what JSON is here: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON 

This issue is open to being worked on for Hacktoberfest, comment below if you have any questions and/or would like to work on it! First come first serve.

**Comment by cmarchena** [comment]
Hello @cBridges851 could please assign me this issue?
Thanks!

**Comment by gitssz** [comment]
Hello @cBridges851 please assign this to me

**Comment by cBridges851** [comment]
Hi both, thanks for your interest in this issue! I'm going to assign this to @cmarchena purely just because he commented first - apologies I didn't get to this sooner. Good luck, feel free to let me know if you need any help with anything!

However, I do have another issue around creating a test plan that's open @gitssz. Alternatively, let me know if there's anything you're looking to upskill on and I can see about creating an issue for you in this or another repo, or feel free to create an issue if you have any ideas on features that could be added to this repo or if you find a bug.

Thanks both, all the best 😊
