### ISSUE TITLE
How do you resize the images?

### ISSUE THREAD

**Issue by fuzzyfazzy** [cBridges851/tkinter-image-viewer#3]
Hello - great code but the images are cropped. Is there a way to display the full image but resized?

**Comment by cBridges851** [comment]
Hi @fuzzyfazzy, thank you for your question!

There currently isn't a way to do any resizing in the user interface, the size currently depends on the file or the size of the `Label` (I'm not sure that's really the right type for the container that displays the image looking back on this code now, but I digress!) in image-viewer.py and it stays fixed at 500x300 or less.

You're more than welcome to have a go at implementing this functionality if you wish, perhaps as part of [Hacktoberfest](https://hacktoberfest.com/) if you're doing that this year 😊! I probably won't get round to it any time soon 😅, but will happily review any pull requests!

**Comment by fuzzyfazzy** [comment]
Hey! @cBridges851 many thanks for getting back to me. Much appreciated. I was doing some coding tweaks earlier this morning so hopefully I can get working!
Thanks again - great work.

**Comment by cBridges851** [comment]
Thank you so much, enjoy 😊!
