### ISSUE TITLE
Opening images via the image viewer

### ISSUE THREAD

**Issue by cBridges851** [cBridges851/tkinter-image-viewer#4]
**Is your feature request related to a problem? Please describe.**
I always get frustrated when I have to manually put my images inside the images folder in order to view them on the image viewer, and it always involves closing and reopening the application.

**Describe the solution you'd like**
I'd like to be able to open images from the image viewer, much like how you do "File...Open" for a Microsoft Word document.

**Describe alternatives you've considered**
I've not thought of any alternatives to get round this problem, but open to suggestions!

**Additional context**
Possible ways in the UI to open the image files:
Having a menu like this at the top, at the moment with just file and open:
![image](https://user-images.githubusercontent.com/54030147/193459881-aa7c1069-edb2-4c24-b908-585ae576de91.png)
When open is clicked, the file explorer should open.

Or a button with an icon like this inside, which opens the file explorer when clicked:
![image](https://user-images.githubusercontent.com/54030147/193459985-41328bce-24c0-4931-9da8-9f22099b5bbc.png)

~This issue is open to being worked on for Hacktoberfest, comment below if you have any questions and/or would like to work on it! First come first serve.~ - Assigned, but feel free to checkout the other issues currently in the repo or create your own!

**Comment by heySanj** [comment]
Would love to have a crack at this! 🙏

**Comment by cBridges851** [comment]
Hi @heySanj! You are more than welcome to work on this, I'll assign you now 😊!

Please let me know if you have any questions!
