### ISSUE TITLE
Adding requirements.txt file

### ISSUE THREAD

**Issue by sourav9599** [cBridges851/tkinter-image-viewer#7]
Hi, @cBridges851 ,
This is a proposal to add requirements.txt file to the repo. I can see you have mentioned about installing pillow pip package, whereas tk(Tkinter) is a also a pip dependency that needs to be installed before running your application which is not documented in the readme.

i would love to work on this , and also propose a virtual env setup (venv or conda) to isolate the app.

Please provide sign-off if you think this is worth working on.

**Comment by cBridges851** [comment]
Hi @sourav9599 , thank you for this idea!

I'm more than happy to sign off the requirements.txt idea, as I think that would help those who are new to the project, especially if they're also quite new to Python and Tkinter. I'd hugely appreciate if it could be linked in the README and is accessible to people who are new to Python and Tkinter, as it would be great for this repo to be a reference point for beginners! This could include a little bit of detail as to what pip is and what each of the dependencies are for, and linking to the relevant documentation if whoever's reading this file would like to find out more.

As for the virtual env proposal, would you mind creating a new issue and providing more detail on what they are and how the image viewer would benefit from it, please 😊?

In the meantime, I'll assign you to this one for the requirements.txt.

Many thanks!
